### PR TITLE
Support PHP 8.3

### PR DESCRIPTION
**Pull request by deleugpn**
## Description
Support PHP 8.3

## Motivation and Context
Use new PHP version

## How Has This Been Tested?
It hasn't yet, hopefully the pull request will trigger automation tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Basic version maintenance

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dragonmantank** [comment]
We are currently waiting on some updates for Prophecy to make it's way through their libraries (Prophecy has a patch, was waiting for official 8.3 release, and then the phpunit-prophecy bridge should update). Once those are updated we'll be able to update our library officially to 8.3.

I updated the testing matrix in this PR to also drag in 8.3, so we can re-run and merge this once the underlying libraries are updated.

**Comment by deleugpn** [comment]
hey @dragonmantank I just ran all tests on my local machine against PHP 8.3.0 and tests are passing.

Could you please approve the workflow and let me know what else we need to unlock this? I would like to update my project and Vonage is the only pending dependency not supporting PHP 8.3 yet.

image

**Comment by SecondeJK** [comment]
I've approved the run, but not looked if prophecy is updated. I suspect we're close to merging this.

**Review by SecondeJK — APPROVED** [review]
8.3 is now passing, so we can now bump other deps causing issues like JWT

**Comment by SecondeJK** [comment]
OK let's go.

**Pull request merged**
