### PR TITLE
PHP 8 Support

### PR DESCRIPTION
**Pull request by driesvints**
## Description

This PR provides PHP 8 support for this library. Currently in draft until `lcobucci/jwt` has been patched.

## Motivation and Context

We'll need this to make sure we can tag and install `nexmo/nexmo-laravel` with PHP 8 support based on this PR: https://github.com/Nexmo/nexmo-laravel/pull/51

This is needed to provide PHP 8 support for Nexmo Notification Channel in Laravel: https://github.com/laravel/nexmo-notification-channel/pull/39

PHP 8 is released on Thursday.

## How Has This Been Tested?
I've updated the Github Actions workflow to make sure the test suite runs on PHP 8 as well.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dragonmantank** [comment]
Awesome, you are quicker than I am :P

If we need to fork the JWT library and patch ourselves, let me know and I'll drag in a local fork for the time being. I see they are still updating the dependencies but whether that equates to PHP 8 work, not sure. I'm also not adverse to changing that library out, since we insulate the user from the library directly.

**Comment by driesvints** [comment]
@dragonmantank haha no worries.

I'm actually in talks with Luis because we also needed it patched for Passport and league/oauth2-server. Luis has been working really hard the last couple of days on getting it updated for PHP 8. I'll let you know tomorrow or so how things proceed 👍

**Comment by driesvints** [comment]
@dragonmantank I didn't get to this anymore unfortunately. From the looks of the failing tests we'll need to figure out a way to support v4 as well together with v3. I know @lcobucci created a BC layer for v4 in v3 so I'm mentioning him here to see if he knows what we need to do. Mostly swapping out the Builder in `Keypair` I believe.

I can look at this again on Thursday at the earliest.

**Comment by lcobucci** [comment]
> Mostly swapping out the Builder in Keypair I believe.

That and using `DateTimeImmutable` objects for registered claims that use dates (`exp`, `iat`, and `nbf`) :+1:

**Comment by dragonmantank** [comment]
@lcobucci Ran through the upgrade docs on this side, thank you for the upgrade docs. Super helpful. Got everything updated in a few minutes, it took longer to run and fix the tests!

Biggest issue I see is that casting to a string is gone, replaced with `$token->toString()`. Is casting going to be available in 3.4.0? That's the only big BC change I see for our users (there are a decent number that generate the tokens using the SDK for their own requests instead of filtering everything through the SDK).

**Comment by dragonmantank** [comment]
@driesvints Just FYI, I'll probably have some unit tests that I'll need to PR against your branch once everything settles down.

**Comment by lcobucci** [comment]
> @lcobucci Ran through the upgrade docs on this side, thank you for the upgrade docs. Super helpful. Got everything updated in a few minutes, it took longer to run and fix the tests!

@dragonmantank Fantastic! Really happy to hear the docs helped :tada: 

>  Is casting going to be available in 3.4.0?

v3.4 still has the casting to string behaviour, annotated with a `@deprecated`, so no BC break there. If the users do want to upgrade to v4.0, then BC-breaks are expected.

**Comment by driesvints** [comment]
Hey sorry, only got back to this PR now.

@dragonmantank ah cool, does that mean you already wrote the code for this PR? Otherwise I can check into patching stuff if you like.

**Comment by dragonmantank** [comment]
@driesvints  Pushed the few test changes and locked to non-dev versions of the branches. Tests pass, so if you're good just mark it ready and I'll get this merged and push releases some time today (it's almost time for turkey) :turkey: :plate_with_cutlery:

**Comment by driesvints** [comment]
@dragonmantank awesome! Not urgent at all. Enjoy thanksgiving! 🙂 

@lcobucci thanks for your help here as well!

**Comment by dragonmantank** [comment]
Merged, and 2.7.0 has been cut!

Will deal with `nexmo/laravel` by Monday. Thank you @driesvints and @lcobucci !

**Pull request merged**
