### PR TITLE
Fix C with Cedilla GSM code point

### PR DESCRIPTION
**Pull request by Starfox64**
## Description
EncodingDetector incorrectly uses the lowercase version of `Latin Small Letter C with Cedilla (U+00E7)` instead of `Latin Capital Letter C with Cedilla (U+00C7)`.

See https://en.wikipedia.org/wiki/GSM_03.38#GSM_7-bit_default_alphabet_and_extension_table_of_3GPP_TS_23.038_/_GSM_03.38

## Motivation and Context
Prevents sending characters that require unicode encoding to be sent as text, causing invalid characters to be displayed in an SMS.

## How Has This Been Tested?
Manual call to `EncodingDetector::requiresUnicodeEncoding()` after correcting the list.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Starfox64** [comment]
Hello, anything blocking this PR?

**Comment by SecondeJK** [comment]
I've enabled the test runner - can you please fix the tests accordingly?

**Review by SecondeJK — CHANGES_REQUESTED** [review]
The test suite is still failing - can you update the tests to pass and run locally before pushing? Thanks

**Comment by Starfox64** [comment]
Fixed, tests are passing locally.

**Comment by SecondeJK** [comment]
Awesome, thanks for this

**Pull request merged**
